### PR TITLE
fix: invalid value serialization when input property is not provided

### LINKED ISSUE #10: Unwanted validationErrors for null value on nullable type
```gql
  type Mutation {
    createBook(book: BookInput): Book!
  }

  input BookInput {
    title: String! @stringLength(max: 5)
    description: String
  }
```

```gql
mutation {
  createBook(book: {
    title: "ddd"
  }) {
    title,
  }
}
```

The `createBook` resolver receives a `validationErrors` on `description` input field: `TypeError: String cannot represent value: undefined` whereas it was not provided.

See this sandbox for [reproduction](https://codesandbox.io/s/unwanted-validation-errors-p4r0m?file=/index.js).

### PR DESCRIPTION
**Pull request by cabelitos**
When an input property is not provided its value won't be set to null,
it will be set to undefined. This would cause the ValidateDirectiveVisitor
to try to serialize the value or in case of more complex types, try to
validate it as well.
In order to avoid these cases, undefined must also be tested.

Closes #10

### CODE REVIEW

File: lib/ValidateDirectiveVisitor.ts [hunk 1]
```diff
@@ -317,7 +317,7 @@ const validateEntryValueThrowing = <TContext>(
     type = type.ofType;
   }
 
-  if (value === null) {
+  if (value === null || value === undefined) {
```
Comment (barbieri) [inline lib/ValidateDirectiveVisitor.ts:320]: I think it’s better to return `value`, no?

Comment (cabelitos) [reply lib/ValidateDirectiveVisitor.ts:320]: indeed. I'm sorry.
